src/objects/Order__c.object
<CustomObject>
    <description>Customer orders</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Pending for Payment</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Payment Review</fullName>
                </value>
                <value>
                    <fullName>Closed Won</fullName>
                </value>
                <value>
                    <fullName>Shipped</fullName>
                </value>
                <value>
                    <fullName>Closed Lost</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Timestamp__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <description>Date/Time of order creation</description>
        <inlineHelpText>Date/Time of order creation</inlineHelpText>
        <label>Timestamp</label>
        <type>DateTime</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>ORD-{000000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Order_Line_Item__c.object
<CustomObject>
    <description>Every product on the order is referenced by a record that includes quantity and a reference to which order it belongs</description>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Order Line Items</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OLI-{000000}</displayFormat>
        <label>Order Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/OrderController.cls
/**
 * Created by oberegovskyi on 27-Oct-18.
 */

public with sharing class OrderController {

    @AuraEnabled
    public static void saveOrderLineItems(List<Order_Line_Item__c> orderLineItems) {

        try {
            Order__c order = new Order__c();
            order.Timestamp__c = Datetime.now();
            order.Status__c = 'New';
            insert order;

            for (Order_Line_Item__c orderLineItem : orderLineItems) {
                orderLineItem.Order__c = order.Id;
            }

            insert orderLineItems;
        } catch (DmlException ex) {
            throw new AuraHandledException(ex.getMessage());
        }

    }
}